<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html>
<head>
<style type="text/css" xml:space="preserve">
table { border-collapse: collapse; } th, td { border-right: 1px solid #aaa; padding: 0px 3px 0px 3px; white-space: nowrap; font-size: 0.9em; } th { white-space: normal; padding: 3px 3px 3px 3px; font-size: 0.95em; } tr:hover {background-color: #c8c8c8; } </style>
<title>Little Navmap - </title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /></head>
<body>
<h1>Scottsdale (KSDL) to Falcon (KFFZ)</h1>
<p><b>Cruising altitude </b>4,000 ft, <b> departure to top of climb </b>6.7 NM, <b> start of descent to destination </b>11.2 NM.<br/><b>Distance </b>35 NM, <b>time </b>0 h 09 m.<p/><p><b>Takeoff</b> from <b>03</b>, 34°M, 8,249 ft.<br/><b>Depart</b> runway <b>03</b> using SID <b>MRRIC1</b>.<br/><b>Arrive </b> via <b>RNAV</b>&nbsp;<b>PEVDE</b><b> (R04L)</b> at runway <b>04L</b>.<br/><b>Land</b> at <b>04L</b>, 41°M, 3,799 ft, 1,394 ft elevation.</p><table border="0" cellpadding="2" cellspacing="0">
<tbody>
<tr bgcolor="#c0c0c0">
<th></th>
<th>Ident</th>
<th>Name</th>
<th>Procedure</th>
<th>Airway or<br/>Procedure</th>
<th>Restriction<br/>ft/kts/angle</th>
<th>Type</th>
<th>Freq.<br/>MHz/kHz/Cha.</th>
<th>Range<br/>NM</th>
<th>Course<br/>°M</th>
<th>Distance<br/>NM</th>
<th>Remaining<br/>NM</th>
<th>Leg Time<br/>hh:mm</th>
<th>ETA<br/>hh:mm</th>
<th>Fuel Rem.<br/>lbs</th>
<th>Fuel Rem.<br/>gal</th>
<th>Wind<br/>°M/kts</th>
<th>Head- or Tailwind<br/>kts</th>
<th>Related<br/>Ident/Freq./Dist./Bearing</th>
<th>Remarks</th>
</tr>
<tr bgcolor="#eceae8"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAACXBIWXMAAAsTAAALEwEAmpwYAAAHsUlEQVQ4EQGmB1n4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUB/FAMHAxsAAAAA/fn95fPAgewAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXRosL+P/3awABAFwAAAAtAAAAAAAAAAAAAAAAAAAB0gAAAKQKBvyV57SB9gAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAD0WDRv8B/58BAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAOYB/wFh8bt9ugAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAABBHgWEAAACpAQAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAADQABAFoJJEDj+N3A0AAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAPRYNGAAH/tgAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwkGAGJLMwD4+vsAn7XOAPz9/v0A/wFK8bt9ugAAAAAAAAAAAQAAAAAAAAAAF0aLC/cA99oBAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkHBQCthVoAOi0eAAAAAABgha0AsMLWAP8AAOYLBv0l57SB9gAAAAACAAAAAAAAAAD4//drAQAAGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBgQAp4FXADotHgAAAAAAAAAAAOzw9QAAAAAAAQAAGvb6BGsAAAAAAAAAAAIAAAAAAAAAAAABAVsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgQDAKF9VABAMSEAAAAAAAAAAACVrcgAxdPhAAAAAAAAAAAAAAD/WwAAAAAAAAAAAQAAAAANQH8UAgYD6wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQDAgCfe1MATTsoAAAAAAAAAAAAnLPMAHWVtwD//wAAAAAAAAAAAAAAAAAA/v0EFPO9eu0CAAAAAAMHAxsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAgEAmHVPAE07KAAAAAAAAAAAAKO4zwB2lbgA//8AAAAAAAAAAAAAAAAAAAAAAAADBPwcAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEBAJJxTABUQSwAAAAAAAAAAACrv9QAcJG1AP7//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAD9+f3lAAAAAAAAAAAAAAAAAAAAAAEBAACLbEkAW0YwAAAAAAAAAAAAssTXAGmLsQD9/v8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/fwE5AAAAAACAAAAAPPAgewAAAHSAAAAAAAAAAABAQAAhWZGAGNMMwAAAAAAAAAAALjJ2wBkh68A/P3+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANHzvXrtAAAAAAIAAAAAAAAAAAD//6UAAAAAAAAAADwuIABqUjcAAAAAAAAAAAC/zt4AYISsAPr8/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpQAAAAAAAAAAAgAAAAAAAAAACAEJlf8AAOYAAAAAEw8KAAAAAAAAAAAAxdLhAFqAqgD4+vwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAOYKBvyVAAAAAAAAAAABAAAAAAAAAAAAAAAAD0WDRgAB/7YFBAIDX0kyAAgGBACetc0A9vj7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9AAD/SfG6f7sAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAEEeBYf//AZsAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/QEB/2XwuX+fAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAD43cDQCCJCyP8BAEMBAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAOYBAP9V8bp/rQAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAD53r/dEik+mPv9A/EAAAEXAAAAFwAAAAAAAAAAAAAAAAAAANEAAAGOCwb9Xey3gNkAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANQ4YTAwT8HAAAAAD9/ATk87167QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABl3OttixQVlwAAAABJRU5ErkJggg==' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000000">KSDL</span></b></td>
<td><span style="color:#000000">Scottsdale</span></td>
<td><span style="color:#000000">Departure</span></td>
<td><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000">0.0</span></td>
<td align="right"><span style="color:#000000">35</span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000">0:00</span></td>
<td align="right"><span style="color:#000000">247</span></td>
<td align="right"><span style="color:#000000">37</span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td><span style="color:#000000"></span></td>
<td><small><span style="color:#000000"></span></small></td>
</tr>
<tr bgcolor="#f3f3f3"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVCQICAh0AAAAA/v7+46urq/cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAgICiwEBAUoAAAAHAAAAAAAAAPkAAAC1/f39dqmpqd0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFaWlplAAAAjgAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPUAAABypqammwAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADgAQEBmv39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAwMD0QAAAAsBAQGq+vr6Y6urq/QAAAAAAAAAAAAAAABVVVUMBgYGnf///1YAAAD1AAAALqampt4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDigAAAAsAAADg+vr6Y6urq/QAAAAAAAAAAAAAAAAAAAAAq6ur9Pr6+mMAAADhAAAACwAAAIsAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAVVVVCQAAAEsAAAAAAQEBmqurq/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACrq6v0AQEBmQAAAAAAAABLYGBgCAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAICAh0AAAAHAAAAAP39/dIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP39/dIAAAAAAAAAB/f39x4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAA/v7+4wAAAPkAAAAAAwMDLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDLgAAAAAAAAD5CQkJ4gAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAKurq/cAAAC1AAAAAP///2ZVVVUMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYmJiDf///2cAAAAAAAAAtaCgoPgAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAA/f39dgAAAPUAAAAgBgYGnVVVVQwAAAAAAAAAAAAAAAAAAAAAYmJiDfn5+ZwAAAAfAAAA9QAAAHUAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADhAQEBmf39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVtbW2T///+PAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9QEBAXGlpaWcAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADT09POKioqqQICAhwAAAAiAAAABAAAAAAAAAD5AAAAsgAAAFKmpqa9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGBgCPf39x4AAAAACQkJ4qCgoPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3HeqpHoq7PoAAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000080">RW03</span></b></td>
<td><span style="color:#000080"></span></td>
<td><span style="color:#000080">SID MRRIC1</span></td>
<td><span style="color:#000080">Proceed to runway</span></td>
<td align="right"><span style="color:#000080">1,510</span></td>
<td><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080">348</span></td>
<td align="right"><span style="color:#000080">0.7</span></td>
<td align="right"><span style="color:#000080">34</span></td>
<td align="right"><span style="color:#000080">0:00</span></td>
<td align="right"><span style="color:#000080">0:00</span></td>
<td align="right"><span style="color:#000080">245</span></td>
<td align="right"><span style="color:#000080">37</span></td>
<td align="right"><span style="color:#000080">251 / 8</span></td>
<td align="right"><span style="color:#000080">&#9660; 7</span></td>
<td><span style="color:#000080"></span></td>
<td><small><span style="color:#000080"></span></small></td>
</tr>
<tr bgcolor="#eceae8"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVCQICAh0AAAAA/v7+46urq/cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAgICiwEBAUoAAAAHAAAAAAAAAPkAAAC1/f39dqmpqd0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFaWlplAAAAjgAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPUAAABypqammwAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADgAQEBmv39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAwMD0QAAAAsBAQGq+vr6Y6urq/QAAAAAAAAAAAAAAABVVVUMBgYGnf///1YAAAD1AAAALqampt4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDigAAAAsAAADg+vr6Y6urq/QAAAAAAAAAAAAAAAAAAAAAq6ur9Pr6+mMAAADhAAAACwAAAIsAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAVVVVCQAAAEsAAAAAAQEBmqurq/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACrq6v0AQEBmQAAAAAAAABLYGBgCAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAICAh0AAAAHAAAAAP39/dIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP39/dIAAAAAAAAAB/f39x4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAA/v7+4wAAAPkAAAAAAwMDLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDLgAAAAAAAAD5CQkJ4gAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAKurq/cAAAC1AAAAAP///2ZVVVUMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYmJiDf///2cAAAAAAAAAtaCgoPgAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAA/f39dgAAAPUAAAAgBgYGnVVVVQwAAAAAAAAAAAAAAAAAAAAAYmJiDfn5+ZwAAAAfAAAA9QAAAHUAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADhAQEBmf39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVtbW2T///+PAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9QEBAXGlpaWcAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADT09POKioqqQICAhwAAAAiAAAABAAAAAAAAAD5AAAAsgAAAFKmpqa9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGBgCPf39x4AAAAACQkJ4qCgoPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3HeqpHoq7PoAAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000080"></span></b></td>
<td><span style="color:#000080"></span></td>
<td><span style="color:#000080">SID MRRIC1</span></td>
<td><span style="color:#000080">Course to altitude</span></td>
<td align="right"><span style="color:#000080">A 1,910</span></td>
<td><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080">32</span></td>
<td align="right"><span style="color:#000080">2.0</span></td>
<td align="right"><span style="color:#000080">32</span></td>
<td align="right"><span style="color:#000080">0:01</span></td>
<td align="right"><span style="color:#000080">0:01</span></td>
<td align="right"><span style="color:#000080">242</span></td>
<td align="right"><span style="color:#000080">36</span></td>
<td align="right"><span style="color:#000080">247 / 8</span></td>
<td align="right"><span style="color:#000080">&#9650; 7</span></td>
<td><span style="color:#000080"></span></td>
<td><small><span style="color:#000080"></span></small></td>
</tr>
<tr bgcolor="#f3f3f3"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVCQICAh0AAAAA/v7+46urq/cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAgICiwEBAUoAAAAHAAAAAAAAAPkAAAC1/f39dqmpqd0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFaWlplAAAAjgAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPUAAABypqammwAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADgAQEBmv39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAwMD0QAAAAsBAQGq+vr6Y6urq/QAAAAAAAAAAAAAAABVVVUMBgYGnf///1YAAAD1AAAALqampt4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDigAAAAsAAADg+vr6Y6urq/QAAAAAAAAAAAAAAAAAAAAAq6ur9Pr6+mMAAADhAAAACwAAAIsAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAVVVVCQAAAEsAAAAAAQEBmqurq/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACrq6v0AQEBmQAAAAAAAABLYGBgCAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAICAh0AAAAHAAAAAP39/dIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP39/dIAAAAAAAAAB/f39x4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAA/v7+4wAAAPkAAAAAAwMDLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDLgAAAAAAAAD5CQkJ4gAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAKurq/cAAAC1AAAAAP///2ZVVVUMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYmJiDf///2cAAAAAAAAAtaCgoPgAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAA/f39dgAAAPUAAAAgBgYGnVVVVQwAAAAAAAAAAAAAAAAAAAAAYmJiDfn5+ZwAAAAfAAAA9QAAAHUAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADhAQEBmf39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVtbW2T///+PAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9QEBAXGlpaWcAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADT09POKioqqQICAhwAAAAiAAAABAAAAAAAAAD5AAAAsgAAAFKmpqa9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGBgCPf39x4AAAAACQkJ4qCgoPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3HeqpHoq7PoAAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000080"></span></b></td>
<td><span style="color:#000080"></span></td>
<td><span style="color:#000080">SID MRRIC1</span></td>
<td><span style="color:#000080">Heading to intercept</span></td>
<td align="right"><span style="color:#000080"></span></td>
<td><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080">220</span></td>
<td align="right"><span style="color:#000080">9.3</span></td>
<td align="right"><span style="color:#000080">23</span></td>
<td align="right"><span style="color:#000080">0:02</span></td>
<td align="right"><span style="color:#000080">0:03</span></td>
<td align="right"><span style="color:#000080">228</span></td>
<td align="right"><span style="color:#000080">34</span></td>
<td align="right"><span style="color:#000080">241 / 7</span></td>
<td align="right"><span style="color:#000080">&#9660; 7</span></td>
<td><span style="color:#000080"></span></td>
<td><small><span style="color:#000080"></span></small></td>
</tr>
<tr bgcolor="#eceae8"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8CAAD/AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAH5XAADC0wAAwG0AAEG4AADA6QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8BAAABhwAAQKwAAEAFAADAwgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAACB5wAA/xgAAAAAAAAA/wAA/5YAAIBuAAAB/gAAAAAAAAAAAAAAAAAAAAAAAIQ0AAD9sgAA/xkAAAAAAAAA/wAACBEAAHjxAAAAAAAAAAABAAAAAAAAAAAAAAAAAACCXAAA/qMAAAAAAAAAAAAA/wAAAAEAAAAA9gAA/6MAAAAAAAAAAAAAAAAAAAI8AAD/KwAA/wAAAAEAAAAAAAAAAAAAAACqAACAVwAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAgOkAAAAWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHpAAD/AAAAAAAAAAAAAAD/DgAAAQkAAAAAAAAAAAAAAAAAAAD/AAAA/wAABhgAAHrrAAAAAAQAAAAAAAAAAAAAfmEAAAAWAAAAAAAAAAAAAAAAAAAAAAAAAP8AAP+YAACAagAAAAAAAAAAAAAAAAAAfzAAAADPAAAAAAAAAAAAAAAAAAAAAQAAAAEAAPufAAAATAAAAAACAAAAAAAAAAAAAAKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAigAAAAAAAAAAAAAAAAAAAAAAAIHQAAAAtgAA//0AAAAAAAAAAAAAAAAAAAAAAAD/SwAAhBsAAAAABAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAD+AAABogAAgOAAAKoDAADVPQAAAgEAACnCAABW/QAAAoQAAP5KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8tAAAA5QIAAAAAAAAAAAAACyoAAP/bAAAAAAAA/wAAAAAAAAAAAQAAA4gAAKoDAADWtAAAAb8AAP++AADWtwAAfwQAAH7HAAAAwAAA//0AAAAAAAD/AAAAAf8AAP+dAAB8ugAAAAACAAAAAAAAAAAAAHXqAACBJgAA/5UAAAAAAAAAAAAAALsAAH3ZAADVPQAAAEgAAAAAAAAAAAAAAEUAAABAAAAAAAAAA4MAAAEDAAAAAAAAAewAAPw3AACBZAAAAf4AAAAAAgAAAAAAAAAAAAAAAAAAAAAAAIFsAAACRAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAMAAAH8XAACDywAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIB2AAAAiQAAADcAACrNAADWtAAAAEgAAAAAAAAAuwAA/0oAAAD+AAABzwAA/wkAAAAqAACB/AAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALlQAAAOwAAP+AAABW/QAAKkwAAP9BAAABQgAAKkkAAIH8AAACUQAAAC4AAAGCAACB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIF1AAD/igAA/zkAAIHIAAAAAAAAAAAAAAAAAAB/AgAAAdEAAAAGAAD/KwAAgfwAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACLCwAA9d4AAAHZAAD+dgAAAAAAAAAAAAAAAAAAAEIAAAGFAAABXAAAf6UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIGoAAD/VwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgQAAFb9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+6gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAFb9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACHMwAA+BcAAAAAAAAAAAAAAAAAAAAAAAAAvgAAgfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6+ieLhTlROIAAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000080">PXR</span></b></td>
<td><span style="color:#000080">Phoenix</span></td>
<td><span style="color:#000080">SID MRRIC1</span></td>
<td><span style="color:#000080">Course to fix</span></td>
<td align="right"><span style="color:#000080">A 4,000</span></td>
<td><span style="color:#000080">VORTAC (H)</span></td>
<td align="right"><span style="color:#000080">115.60</span></td>
<td align="right"><span style="color:#000080">250</span></td>
<td align="right"><span style="color:#000080">141</span></td>
<td align="right"><span style="color:#000080">7.5</span></td>
<td align="right"><span style="color:#000080">15.6</span></td>
<td align="right"><span style="color:#000080">0:01</span></td>
<td align="right"><span style="color:#000080">0:04</span></td>
<td align="right"><span style="color:#000080">220</span></td>
<td align="right"><span style="color:#000080">33</span></td>
<td align="right"><span style="color:#000080">244 / 8</span></td>
<td align="right"><span style="color:#000080">&#9650; 2</span></td>
<td><span style="color:#000080">PXR, 115.60 MHz</span></td>
<td><small><span style="color:#000080"></span></small></td>
</tr>
<tr bgcolor="#f3f3f3"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BL8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAAAAAAogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAAPcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8ECQAJ1wAAACQAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADfAAAA3wAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BAkACdcAAAAkAQABXwAAAAD/AP+hAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qb2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwT/AP99AAAAAAEAAYNBAEH8QQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAANz2APamAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8E/wD/fQAAAAABAAGDQQBB/AAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADc9gD2pgAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BP8A/30AAAAAAQABg0EAQfwAAAAAAAAAAAAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAIAAhcAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQKAApbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnIhrWmcjrX4AAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000080">ISTOW (FACF)</span></b></td>
<td><span style="color:#000080"></span></td>
<td><span style="color:#000080">Approach RNAV PEVDE</span></td>
<td><span style="color:#000080">Initial fix</span></td>
<td align="right"><span style="color:#000080">A 3,200</span></td>
<td><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080">120</span></td>
<td align="right"><span style="color:#000080">6.5</span></td>
<td align="right"><span style="color:#000080">9.1</span></td>
<td align="right"><span style="color:#000080">0:02</span></td>
<td align="right"><span style="color:#000080">0:06</span></td>
<td align="right"><span style="color:#000080">213</span></td>
<td align="right"><span style="color:#000080">32</span></td>
<td align="right"><span style="color:#000080">254 / 9</span></td>
<td align="right"><span style="color:#000080">&#9650; 6</span></td>
<td><span style="color:#000080"></span></td>
<td><small><span style="color:#000080"></span></small></td>
</tr>
<tr bgcolor="#eceae8"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BL8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAAAAAAogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAAPcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8ECQAJ1wAAACQAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADfAAAA3wAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BAkACdcAAAAkAQABXwAAAAD/AP+hAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qb2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwT/AP99AAAAAAEAAYNBAEH8QQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAANz2APamAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8E/wD/fQAAAAABAAGDQQBB/AAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADc9gD2pgAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BP8A/30AAAAAAQABg0EAQfwAAAAAAAAAAAAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAIAAhcAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQKAApbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnIhrWmcjrX4AAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000080">PEVDE (FAF)</span></b></td>
<td><span style="color:#000080"></span></td>
<td><span style="color:#000080">Approach RNAV PEVDE</span></td>
<td><span style="color:#000080">Track to fix</span></td>
<td align="right"><span style="color:#000080">A 2,300</span></td>
<td><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080">40</span></td>
<td align="right"><span style="color:#000080">6.3</span></td>
<td align="right"><span style="color:#000080">2.8</span></td>
<td align="right"><span style="color:#000080">0:02</span></td>
<td align="right"><span style="color:#000080">0:08</span></td>
<td align="right"><span style="color:#000080">205</span></td>
<td align="right"><span style="color:#000080">31</span></td>
<td align="right"><span style="color:#000080">256 / 10</span></td>
<td align="right"><span style="color:#000080">&#9650; 8</span></td>
<td><span style="color:#000080"></span></td>
<td><small><span style="color:#000080"></span></small></td>
</tr>
<tr bgcolor="#f3f3f3"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BL8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAAAAAAogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAAPcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8ECQAJ1wAAACQAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADfAAAA3wAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BAkACdcAAAAkAQABXwAAAAD/AP+hAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qb2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwT/AP99AAAAAAEAAYNBAEH8QQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAANz2APamAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8E/wD/fQAAAAABAAGDQQBB/AAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADc9gD2pgAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BP8A/30AAAAAAQABg0EAQfwAAAAAAAAAAAAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAIAAhcAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQKAApbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnIhrWmcjrX4AAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000080">ZENAM (MAP)</span></b></td>
<td><span style="color:#000080"></span></td>
<td><span style="color:#000080">Approach RNAV PEVDE</span></td>
<td><span style="color:#000080">Track to fix</span></td>
<td align="right"><span style="color:#000080">1,660, -3&#176;</span></td>
<td><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080">41</span></td>
<td align="right"><span style="color:#000080">2.0</span></td>
<td align="right"><span style="color:#000080">0.8</span></td>
<td align="right"><span style="color:#000080">0:01</span></td>
<td align="right"><span style="color:#000080">0:09</span></td>
<td align="right"><span style="color:#000080">202</span></td>
<td align="right"><span style="color:#000080">30</span></td>
<td align="right"><span style="color:#000080">257 / 10</span></td>
<td align="right"><span style="color:#000080">&#9650; 8</span></td>
<td><span style="color:#000080"></span></td>
<td><small><span style="color:#000080"></span></small></td>
</tr>
<tr bgcolor="#eceae8"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVCQICAh0AAAAA/v7+46urq/cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAgICiwEBAUoAAAAHAAAAAAAAAPkAAAC1/f39dqmpqd0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFaWlplAAAAjgAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPUAAABypqammwAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADgAQEBmv39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAwMD0QAAAAsBAQGq+vr6Y6urq/QAAAAAAAAAAAAAAABVVVUMBgYGnf///1YAAAD1AAAALqampt4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDigAAAAsAAADg+vr6Y6urq/QAAAAAAAAAAAAAAAAAAAAAq6ur9Pr6+mMAAADhAAAACwAAAIsAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAVVVVCQAAAEsAAAAAAQEBmqurq/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACrq6v0AQEBmQAAAAAAAABLYGBgCAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAICAh0AAAAHAAAAAP39/dIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP39/dIAAAAAAAAAB/f39x4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAA/v7+4wAAAPkAAAAAAwMDLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDLgAAAAAAAAD5CQkJ4gAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAKurq/cAAAC1AAAAAP///2ZVVVUMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYmJiDf///2cAAAAAAAAAtaCgoPgAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAA/f39dgAAAPUAAAAgBgYGnVVVVQwAAAAAAAAAAAAAAAAAAAAAYmJiDfn5+ZwAAAAfAAAA9QAAAHUAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADhAQEBmf39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVtbW2T///+PAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9QEBAXGlpaWcAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADT09POKioqqQICAhwAAAAiAAAABAAAAAAAAAD5AAAAsgAAAFKmpqa9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGBgCPf39x4AAAAACQkJ4qCgoPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3HeqpHoq7PoAAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000080">RW04L</span></b></td>
<td><span style="color:#000080"></span></td>
<td><span style="color:#000080">Approach RNAV PEVDE</span></td>
<td><span style="color:#000080">Straight in</span></td>
<td align="right"><span style="color:#000080">1,444</span></td>
<td><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080"></span></td>
<td align="right"><span style="color:#000080">41</span></td>
<td align="right"><span style="color:#000080">0.8</span></td>
<td align="right"><span style="color:#000080">0.0</span></td>
<td align="right"><span style="color:#000080">0:00</span></td>
<td align="right"><span style="color:#000080">0:09</span></td>
<td align="right"><span style="color:#000080">201</span></td>
<td align="right"><span style="color:#000080">30</span></td>
<td align="right"><span style="color:#000080">257 / 10</span></td>
<td align="right"><span style="color:#000080">&#9650; 8</span></td>
<td><span style="color:#000080"></span></td>
<td><small><span style="color:#000080"></span></small></td>
</tr>
<tr bgcolor="#f3f3f3"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVCQICAh0AAAAA/v7+46urq/cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAgICiwEBAUoAAAAHAAAAAAAAAPkAAAC1/f39dqmpqd0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFaWlplAAAAjgAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPUAAABypqammwAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADgAQEBmv39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAABXV1cjAwMD0QAAAAsBAQGq+vr6Y6urq/QAAAAAAAAAAAAAAABVVVUMBgYGnf///1YAAAD1AAAALqampt4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDigAAAAsAAADg+vr6Y6urq/QAAAAAAAAAAAAAAAAAAAAAq6ur9Pr6+mMAAADhAAAACwAAAIsAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAVVVVCQAAAEsAAAAAAQEBmqurq/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACrq6v0AQEBmQAAAAAAAABLYGBgCAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAICAh0AAAAHAAAAAP39/dIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP39/dIAAAAAAAAAB/f39x4AAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAA/v7+4wAAAPkAAAAAAwMDLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDLgAAAAAAAAD5CQkJ4gAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAKurq/cAAAC1AAAAAP///2ZVVVUMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYmJiDf///2cAAAAAAAAAtaCgoPgAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAA/f39dgAAAPUAAAAgBgYGnVVVVQwAAAAAAAAAAAAAAAAAAAAAYmJiDfn5+ZwAAAAfAAAA9QAAAHUAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaWlpmAAAAmQAAAAAAAADhAQEBmf39/dIAAAAAAwMDLv///2cAAAAfAAAAAAEBAWalpaWbAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVtbW2T///+PAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9QEBAXGlpaWcAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADT09POKioqqQICAhwAAAAiAAAABAAAAAAAAAD5AAAAsgAAAFKmpqa9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGBgCPf39x4AAAAACQkJ4qCgoPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3HeqpHoq7PoAAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#800000"></span></b></td>
<td><span style="color:#800000"></span></td>
<td><span style="color:#800000">Missed RNAV PEVDE</span></td>
<td><span style="color:#800000">Course to altitude</span></td>
<td align="right"><span style="color:#800000">A 1,780</span></td>
<td><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000">39</span></td>
<td align="right"><span style="color:#800000">2.0</span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td><span style="color:#800000"></span></td>
<td><small><span style="color:#800000"></span></small></td>
</tr>
<tr bgcolor="#eceae8"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BL8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAAAAAAogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAAPcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8ECQAJ1wAAACQAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADfAAAA3wAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BAkACdcAAAAkAQABXwAAAAD/AP+hAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qb2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwT/AP99AAAAAAEAAYNBAEH8QQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAANz2APamAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8E/wD/fQAAAAABAAGDQQBB/AAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADc9gD2pgAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BP8A/30AAAAAAQABg0EAQfwAAAAAAAAAAAAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAIAAhcAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQKAApbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnIhrWmcjrX4AAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#800000">SACAT</span></b></td>
<td><span style="color:#800000"></span></td>
<td><span style="color:#800000">Missed RNAV PEVDE</span></td>
<td><span style="color:#800000">Direct to fix</span></td>
<td align="right"><span style="color:#800000">A 5,000</span></td>
<td><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000">15.2</span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td><span style="color:#800000"></span></td>
<td><small><span style="color:#800000"></span></small></td>
</tr>
<tr bgcolor="#f3f3f3"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BL8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAAAAAAogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAAPcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8ECQAJ1wAAACQAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADfAAAA3wAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BAkACdcAAAAkAQABXwAAAAD/AP+hAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qb2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL8AvwT/AP99AAAAAAEAAYNBAEH8QQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAApaAAAAJAAAANz2APamAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AL8E/wD/fQAAAAABAAGDQQBB/AAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAKWgAAACQAAADc9gD2pgAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAvwC/BP8A/30AAAAAAQABg0EAQfwAAAAAAAAAAAAAAAAAAAAAQQBB/AEAAYMAAAAA/wD/fb8AvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAoACloAAAAkAAAA3PYA9qYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2APamAAAA3AAAACQKAApaAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAL8AvwQJAAnXAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3PcA9ylBAEH8AAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAIAAhcAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQKAApbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnIhrWmcjrX4AAAAASUVORK5CYII=' width="24" height="24"/></td>
<td align="right"><b><span style="color:#800000">SACAT</span></b></td>
<td><span style="color:#800000"></span></td>
<td><span style="color:#800000">Missed RNAV PEVDE</span></td>
<td><span style="color:#800000">Hold to manual termination</span></td>
<td align="right"><span style="color:#800000"></span></td>
<td><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000">323</span></td>
<td align="right"><span style="color:#800000">0.0</span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td align="right"><span style="color:#800000"></span></td>
<td><span style="color:#800000"></span></td>
<td><small><span style="color:#800000"></span></small></td>
</tr>
<tr bgcolor="#eceae8"><td><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAACXBIWXMAAAsTAAALEwEAmpwYAAAHsUlEQVQ4EQGmB1n4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUB/FAMHAxsAAAAA/fn95fPAgewAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXRosL+P/3awABAFwAAAAtAAAAAAAAAAAAAAAAAAAB0gAAAKQKBvyV57SB9gAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAD0WDRv8B/58BAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAOYB/wFh8bt9ugAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAABBHgWEAAACpAQAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAADQABAFoJJEDj+N3A0AAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAPRYNGAAH/tgAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKCAUA9vj7AAAAAP0A/wFK8bt9ugAAAAAAAAAAAgAAAAAAAAAAF0aLC/8B/58AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaFA4AtIteAOSwdwB6XkAAAAAAA/8B/58ZTH8KAAAAAAAAAAACAAAAAAAAAAD4//drAQAAGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOCsdAMCUZAA8Lh8AAgEBAFhELQAAAAAAAQAAGvb6BGsAAAAAAAAAAAIAAAAAAAAAAAABAVsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF9JMgCzil4AFhELAAAAAAAAAAAAk6zHAAAAAAAAAAAAAAD/WwAAAAAAAAAAAQAAAAANQH8UAgYD6wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYEAwCHaUcAY0wzAAAAAAAAAAAA+Pn8AGyPswCsv9QAAAAAAAAAAAAAAAAA/v0EFPO9eu0EAAAAAAMHAxv//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVEAsAoXxUADotHgAAAAAAAAAAAOTq8QBagaoA0tzoAAAAAAAAAAAAAAAAAAAAAAADBPwcAAAA7QQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyQZAKaAVgAbFQ4AAAAAAAAAAADG0+IAX4SsAOvw9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAD9+f3lAgYDAAAAAAAAAAAAAAAAAFRBLACUck0ACAYEAAAAAAAAAAAAm7LMAHqZuQD7/P4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/fwE5AAAAAABAAAAAAAAAAAPRoPRAAD/LgAAAABlTjQAi2tJAAAAAAAAAAAA+/z+AHOUtgCit88AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANHxun4wAAAAAAQAAAAAAAAAAAD//6UAAQAuAAAAAG5VOgAAAAAAAAAAAOrv9QBdgqoAydbkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpQAAAAAAAAAAAgAAAAAAAAAACAEJlf8AAOYAAAAAp7vSAP7//wDE0uEAQGycAMnW5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAOYKBvyVAAAAAAAAAAABAAAAAAAAAAAAAAAAD0WDRgAB/7YAAAADCggFAPb4+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9AAD/SfG6f7sAAAAAAAAAAAMAAAAAAAAAAAAAAAD53r/dCSRA4wAAAUz7/P4CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/QEB/2Xxun+tAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAD43cDQCCJCyP8BAEMBAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAOYBAP9V8bp/rQAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAD53r/dEik+mPv9A/EAAAEXAAAAFwAAAAAAAAAAAAAAAAAAANEAAAGOCwb9Xey3gNkAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANQ4YTAwT8HAAAAAD9/ATk87167QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvL+an2qapSwAAAABJRU5ErkJggg==' width="24" height="24"/></td>
<td align="right"><b><span style="color:#000000">KFFZ</span></b></td>
<td><span style="color:#000000">Falcon</span></td>
<td><span style="color:#000000">Destination</span></td>
<td><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000">0:00</span></td>
<td align="right"><span style="color:#000000">0:09</span></td>
<td align="right"><span style="color:#000000">201</span></td>
<td align="right"><span style="color:#000000">30</span></td>
<td align="right"><span style="color:#000000"></span></td>
<td align="right"><span style="color:#000000"></span></td>
<td><span style="color:#000000"></span></td>
<td><small><span style="color:#000000"></span></small></td>
</tr>
</tbody>
</table>
<p><small>Little Navmap Version 3.0.5 (revision 7461ed3c) on 2 May 2024 5:16:20&#8239;PM +08 </small></p>
</body>
</html>
